// Enums
export type UserRole = 'ADMIN' | 'OWNER' | 'USER';
export type UserType = 'TECHNICIAN' | 'ADMINISTRATION' | 'SELLER';
export type ClientType = 'ATIX' | 'FINAL';
export type WorkStatus = 'SCHEDULED' | 'IN_PROGRESS' | 'CLOSED' | 'INVOICED';
export type TicketStatus = 'OPEN' | 'IN_PROGRESS' | 'RESOLVED' | 'CLOSED';
export type AttachmentType = 'PHOTO' | 'PDF' | 'DOC' | 'OTHER';
export type AttachmentTargetType = 'WORK' | 'PLANT' | 'TICKET' | 'REPORT';
// F6: added MAINTENANCE (manutentore) and OTHER (altro)
export type WorksiteReferenceRole = 'PLUMBER' | 'ELECTRICIAN' | 'MAINTENANCE' | 'OTHER';

// User types
export interface User {
  id: string;
  profileImageUrl?: string;
  firstName: string;
  lastName: string;
  email: string;
  role: UserRole;
  type: UserType;
  calendarColor?: string;
}

export interface TechnicianUser extends User {
  type: 'TECHNICIAN';
}

export interface AdministrativeUser extends User {
  type: 'ADMINISTRATION';
}

export interface SellerUser extends User {
  type: 'SELLER';
  soldWorks?: Work[];
}

// Client & Plant
export interface Client {
  id: string;
  name: string;
  type: ClientType;
}

export interface Plant {
  id: string;
  name: string;
  notes: string;
  nasDirectory: string;
  pswPhrase: string;
  pswPlatform: string;
  pswStation: string;
}

export interface AssignedTechnician {
  id: string;
  technicianId: string;
  technicianFirstName: string;
  technicianLastName: string;
  technicianEmail?: string;
  profileImageUrl?: string;
  assignedAt: string;
}

// Work types
export interface Work {
  id: string;
  name: string;
  description?: string;
  bidNumber: string;
  orderNumber: string;
  orderDate: string;
  atixClientId?: string;
  finalClientId?: string;
  plantId?: string;
  electricalSchemaProgression: number;
  programmingProgression: number;
  expectedStartDate?: string;
  status: WorkStatus;
  statusChangedAt?: string;
  createdAt: string;
  nasSubDirectory: string;
  relatedPlantNasDirectory?: string;
  expectedOfficeHours: number;
  expectedPlantHours: number;
  seller?: SellerUser;
  plant?: Plant;
  atixClient?: Client;
  finalClient?: Client;
  ticket?: Ticket;
  workReport?: WorkReport;
  assignments?: WorkAssignment[];
  assignedTechnicians?: AssignedTechnician[];
}

export interface WorkAssignment {
  id: string;
  assignedAt: string;
  work?: Work;
  user?: User;
}

export interface WorkReport {
  id: string;
  totalHours: number;
  createdAt: string;
  work?: Work;
  entries?: WorkReportEntry[];
}

export interface WorkReportEntry {
  id: string;
  description: string;
  hours: number;
  date: string;
  userId?: string;
  userName?: string;
  report?: WorkReport;
  rapportinoId?: string | null; // set when generated by a signed rapportino (read-only)
}

// Ticket
export interface Ticket {
  id: string;
  senderEmail?: string;
  name: string;
  description: string;
  status: TicketStatus;
  createdAt: string;
  orderNumber?: Work;
  orderNumberId?: string | null; // id of the work created from this ticket, if any
}

// Worksite Reference
export interface WorksiteReference {
  id: string;
  name: string;
  telephone?: string;
  notes?: string;
}

export interface WorksiteReferenceAssignment {
  id: string;
  role: WorksiteReferenceRole;
  work?: Work;
  worksiteReference?: WorksiteReference;
}

// Attachment
export interface Attachment {
  id: string;
  url: string;
  publicId: string;
  originalFilename?: string;
  resourceType: string;
  type: AttachmentType;
  uploadedAt: string;
}

export interface AttachmentLink {
  id: string;
  targetType: AttachmentTargetType;
  targetId: string;
  attachment?: Attachment;
}

// Dashboard
export interface DashboardSummary {
  clientCount: number;
  plantCount: number;
  completedWorkCount: number;
  pendingWorkCount: number;
  workStatusCounts: { status: WorkStatus; count: number }[];
  ticketStatusCounts: { status: TicketStatus; count: number }[];
  recentWorks: Work[];
  recentTickets: Ticket[];
}

// API Response types
export interface PaginatedResponse<T> {
  content: T[];
  totalElements: number;
  totalPages: number;
  size: number;
  number: number;
}

export interface AccessLog {
  id: string;
  userId: string | null;
  userFullName: string | null;
  email: string;
  timestamp: string;
  ipAddress: string;
  userAgent: string;
  success: boolean;
  failureReason: string | null;
  sessionId: string | null;
  logoutTimestamp: string | null;
  jwtExpiresAt: string | null;
}
